language: python

sudo: required

os:
  - linux

env:
  - FLASK_CONFIGURATION=test

before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get remove --purge postgresql-9.1
  - sudo service postgresql start 9.4

python:
  - "2.7"

services:
  - postgresql
addons:
  postgresql: "9.4"

before_script:
  - psql -U postgres -c "create user dpr_user password 'secret' createdb;"
  - psql -U postgres -c "create database dpr_db_test owner=dpr_user;"

install:
  - pip install -r requirements.txt
  - pip install -r requirements.test.txt

script: pytest tests

after_success:
  coveralls
before_deploy:
  - export FLASK_CONFIGURATION=stage
deploy:
  skip_cleanup: true
  provider: script
  script: python zappa_deploy.py
  on:
    repo: frictionlessdata/dpr-api
    branch: master